/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avariju.GUI;

import static avariju.GUI.pagrindinis_langas.con;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import avariju.db.JdbcSQLServerConnection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author tueik
 */
public class pakeisti extends javax.swing.JFrame {

    private String nulinis;
    pagrindinis_langas prg;
    private String val2, val3, val4, val5;
    //public static int miesto_nr;

    public pakeisti(java.awt.Frame parent, boolean modal,String nulinis,String val2, String val3, String val4, String val5) {
        initComponents();
        this.nulinis = nulinis;
          jTextField1.setText(nulinis.toString());
        this.val2 = val2;
         jTextField2.setText(val2.toString());
          this.val3 = val3;
           jTextField3.setText(val3.toString());
          this.val4 = val4;
          jTextField4.setText(val4.toString());
          this.val5 = val5;
              jTextField5.setText(val5.toString());
        
    }

    private pakeisti() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        Updatinti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel3.setText("Pakeisti informaciją:");

        jLabel1.setText("Valstybiniai numeriai:");

        jLabel2.setText("Preliminari žala:");

        jLabel4.setText("Asmens kodas:");

        jLabel5.setText("Markė:");

        jLabel6.setText("Miestas:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        Updatinti.setText("Issaugoti");
        Updatinti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatintiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))))
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Updatinti)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Updatinti)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void UpdatintiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatintiActionPerformed
 String old = nulinis.toString();
  // JOptionPane.showMessageDialog(null,old);
  int miesto_nr = 0;
 try{
   String query = "Select dbo.EISMO_IVYKIS.MIESTO_NR FROM dbo.EISMO_IVYKIS, dbo.EISMO_DALYVIS\n" +
"WHERE dbo.EISMO_DALYVIS.EISMO_IVYKIO_ID= dbo.EISMO_IVYKIS.EISMO_IVYKIO_ID\n" +
"AND dbo.EISMO_DALYVIS.VALSTYBINIAI_NUMERIAI= '" + old + "' ";
  // System.out.println(query);
       // try {
               ResultSet rs = con.getback(query);
         //  int miesto_nr = 0;
            if (rs.next()) {
                             //Integer idParent = (Integer) rs.getObject("MIESTO_NR");    
                           miesto_nr= rs.getInt("MIESTO_NR");
                 // if (idParent!=null) {
                     // miesto_nr=idParent;
                      //System.out.println(miesto_nr);
        // handle NULL field value
    }
                   //  JOptionPane.showMessageDialog(null,miesto_nr);
                   
             
                }catch (SQLException ex) {
                    Logger.getLogger(pakeisti.class.getName()).log(Level.SEVERE, null, ex);
                }
 
    
 
        String val_nr = this.jTextField1.getText();
        
      //   JOptionPane.showMessageDialog(null,miesto_nr);
                   String Szala = this.jTextField2.getText();
                  double zala =Double.parseDouble(Szala);  
                 // double senass = Double.parseDouble(val2);
                 String asmens = this.jTextField3.getText();
                  String marke = this.jTextField4.getText();
                     String miestas = this.jTextField5.getText();
                     con.update("Update Transporto_priemone\n" +
"set Transporto_priemone.VALSTYBINIAI_NUMERIAI = ? \n" +
"WHERE Transporto_priemone.VALSTYBINIAI_NUMERIAI = ? "
                              + "",val_nr,old);
                      
                     con.update1("Update EISMO_DALYVIS\n" +
"set EISMO_DALYVIS.PRELIMINARI_ZALA = ? \n" +
"WHERE EISMO_DALYVIS.VALSTYBINIAI_NUMERIAI = ? "
                              + "",val_nr,zala);
                           
                        con.update3("Update EISMO_DALYVIS\n" +
"set EISMO_DALYVIS.ASMENS_KODAS = ? \n" +
"WHERE EISMO_DALYVIS.VALSTYBINIAI_NUMERIAI = ? "
                              + "",val_nr,asmens);
                       this.dispose(); 
                       
                       con.update3("Update Transporto_priemone\n" +
"set Transporto_priemone.MARKE = ? \n" +
"WHERE Transporto_priemone.VALSTYBINIAI_NUMERIAI = ? "
                              + "",val_nr,marke);
                            
        con.update4("Update IVYKIO_VIETA\n" +
"set IVYKIO_VIETA.MIESTAS = ? \n" +
"WHERE IVYKIO_VIETA.MIESTO_NR = ? "
                              + "",miestas,miesto_nr);
        
                this.dispose();      
                          
    }//GEN-LAST:event_UpdatintiActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pakeisti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pakeisti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pakeisti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pakeisti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pakeisti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Updatinti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
